name: Publish Package

on:
  release:
    types: [released]

jobs:
  build:
    env:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      PYPI_USERNAME: "__token__"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: poetry install

      - name: Build Package
        run: poetry build

      - name: Publish Package
        run: poetry publish -u $PYPI_USERNAME -p $PYPI_TOKEN
